import { Router } from 'express';
import branchRouter from './branch.routes';
import userRouter from './user.routes';
import categoryRouter from './category.routes';
import productRouter from './product.routes';
import customerRouter from './customer.routes';
import restaurantTableRouter from './table.routes';
import discountRouter from './discount.routes';
import orderRouter from './order.routes';
import orderItemRouter from './order-item.routes';
import paymentRouter from './payment.routes';
import inventoryRouter from './inventory.routes';
import stockMovementRouter from './stock-movement.routes';
import shiftSessionRouter from './shift-session.routes';
import expenseRouter from './expense.routes';
import printerRouter from './printer.routes';
import kitchenDisplayRouter from './kitchen-display.routes';
import notificationRouter from './notification.routes';
import auditLogRouter from './audit-log.routes';
import systemRouter from './system.routes';
import ingredientRouter from './ingredient.routes';
import recipeRouter from './recipe.routes';
import purchaseRouter from './purchase.routes';
import cashMovementRouter from './cash-movement.routes';
import hookahRouter from './hookah.routes';

const router = Router();

router.use('/branches', branchRouter);
router.use('/users', userRouter);
router.use('/categories', categoryRouter);
router.use('/products', productRouter);
router.use('/customers', customerRouter);
router.use('/restaurant-tables', restaurantTableRouter);
router.use('/discounts', discountRouter);
router.use('/orders', orderRouter);
router.use('/order-items', orderItemRouter);
router.use('/payments', paymentRouter);
router.use('/inventory', inventoryRouter);
router.use('/stock-movements', stockMovementRouter);
router.use('/shift-sessions', shiftSessionRouter);
router.use('/expenses', expenseRouter);
router.use('/printers', printerRouter);
router.use('/kitchen-displays', kitchenDisplayRouter);
router.use('/notifications', notificationRouter);
router.use('/audit-logs', auditLogRouter);
router.use('/system', systemRouter);
router.use('/ingredients', ingredientRouter);
router.use('/recipes', recipeRouter);
router.use('/purchases', purchaseRouter);
router.use('/cash-movements', cashMovementRouter);
router.use('/hookahs', hookahRouter);

export default router;
